<footer class="footer-standard-dark bg-extra-dark-gray"> 
            
            <div class="bg-dark-footer padding-50px-tb text-center sm-padding-30px-tb">
                <div class="container">
                    <div class="row">
                        <!-- start copyright -->
                        <div class="col-md-6 text-md-left text-small text-center"><a href="index.php" class="margin-20px-bottom d-inline-block"><img class="footer-logo" src="../images/logo-white.png" data-rjs="images/logo-white@2x.png" alt=""></a> &copy; Porpora - Todos los derechos reservados - Powered by <a href="http://www.nectica.com.ar" target="_blank" class="text-dark-gray">Néctica</a></div>
                        <div class="col-md-6 text-md-right text-small text-center">
                            <a href="javascript:void(0);" class="text-dark-gray">Términos y condiciones</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="javascript:void(0);" class="text-dark-gray">Legales</a>
                        </div>
                        <!-- end copyright -->
                    </div>
                </div>
            </div>
        </footer>
</body>
</html>