<header class="header">
                 
            <!-- start navigation -->
    <nav class="navbar navbar-expand-lg navbar-light" id="navbar-proteccion">
        <div class="container-fluid p-2">
            <div class="row">
                <div class="col-xs-6 col-lg-8">
                <a class="navbar-brand" href="#">
                    <img src="../images/logo-white.png" width="80" height="80" class="d-inline-block align-top" alt="">
                </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-lg-2">
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="nav-item nav-link text-light mr-4" href="../ronda/rondas">Rondas</a>
                            <a class="nav-item nav-link text-light mr-4" href="../puntocontrol">Puntocontrol</a>
                            <!--<a class="nav-item nav-link text-light" href="#">Configuracion</a>-->
                        </div>
                    </div>
                </div>   
            </div>
        </div>
    </nav>
            <!-- end navigation --> 
        </header>