<section id="sectionLogin">
    <div class="container">
           <div class="row justify-content-center">
               <div class="col-md-4 pb-5 text-center">
                   <img src="../images/logo.png">
               </div>
            </div>
            <div class="row justify-content-center">
            <strong class="error_login" style="color: red;"></strong>
                <div class="col-md-4">
                    <label>Usuario</label>
                    <input type="input" class="form-control" id="usuario" name="usuario">
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="form-group col-md-4 pt-5">
                    <label>Contraseña</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-4 d-flex justify-content-center">
                    <button  class="envialogin btn btn-primary rounded-pill">Ingresar</button>
                </div>
            </div>
    </div>
</section>